CREATE TABLE IF NOT EXISTS analytics_runs (
	run_id VARCHAR(64) NOT NULL,
	user_id VARCHAR(64) NOT NULL,
	app_session_id VARCHAR(64) NOT NULL,
	content_type VARCHAR(24) NOT NULL,
	content_id VARCHAR(160) NOT NULL,
	difficulty VARCHAR(24) NOT NULL,
	game_mode VARCHAR(24) NOT NULL,
	map_file VARCHAR(255) NOT NULL DEFAULT '',
	scenario_path VARCHAR(255) NOT NULL DEFAULT '',
	victory_condition VARCHAR(80) NOT NULL DEFAULT '',
	status VARCHAR(24) NOT NULL DEFAULT 'started',
	started_ts INT UNSIGNED NOT NULL,
	last_event_ts INT UNSIGNED NOT NULL,
	elapsed_seconds INT UNSIGNED NOT NULL DEFAULT 0,
	turn_count INT UNSIGNED NOT NULL DEFAULT 0,
	winner_player_id INT NULL,
	outcome_reason VARCHAR(80) NOT NULL DEFAULT '',
	build VARCHAR(80) NOT NULL DEFAULT '',
	platform VARCHAR(80) NOT NULL DEFAULT '',
	is_internal TINYINT(1) NOT NULL DEFAULT 0,
	run_source VARCHAR(40) NOT NULL DEFAULT '',
	internal_reason VARCHAR(120) NOT NULL DEFAULT '',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (run_id),
	KEY idx_content_difficulty (content_type, content_id, difficulty),
	KEY idx_user_content (user_id, content_type, content_id),
	KEY idx_status (status),
	KEY idx_is_internal (is_internal),
	KEY idx_last_event_ts (last_event_ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analytics_events (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	event_ts INT UNSIGNED NOT NULL,
	event_name VARCHAR(40) NOT NULL,
	user_id VARCHAR(64) NOT NULL,
	app_session_id VARCHAR(64) NOT NULL,
	run_id VARCHAR(64) NULL,
	content_type VARCHAR(24) NOT NULL DEFAULT '',
	content_id VARCHAR(160) NOT NULL DEFAULT '',
	difficulty VARCHAR(24) NOT NULL DEFAULT '',
	elapsed_seconds INT UNSIGNED NOT NULL DEFAULT 0,
	turn_count INT UNSIGNED NOT NULL DEFAULT 0,
	outcome VARCHAR(24) NOT NULL DEFAULT '',
	payload_json LONGTEXT NOT NULL,
	PRIMARY KEY (id),
	KEY idx_event_name_ts (event_name, event_ts),
	KEY idx_run_id (run_id),
	KEY idx_content (content_type, content_id, difficulty),
	KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
